name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  server-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build .
